# This is the main CI pipeline.
# It lints, builds and runs unit tests for all of our projects.

# Trigger this pipeline on all pushes landing on our primary integration branches.
trigger:
  branches:
    include:
    - main
    - develop
    - release/*

# Trigger this pipeline on PRs against our primary integration branches.
pr:
  - main
  - develop
  - release/*

# The `resources` specify the location and version of the 1ES PT.
resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:

  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      os: windows
      image: windows-2022
      name: Azure-Pipelines-1ESPT-ExDShared
    sdl:
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\guardian\SDL\.gdnsuppress
    stages:
    - stage: Stage
      jobs:
        - job: Job
          steps:
          - task: servicetree-link-build-task@1
            displayName: 'ServiceTree Integration'
            inputs:
              ServiceTreeGateway: 'ServiceTree Gateway'
              Service: 'e312ec77-9c77-48a7-9837-32fe6d08d460'
              BuildOutputUsage: 'test'
          - task: JavaToolInstaller@0
            displayName: 'Configure Java 17'
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'
          - task: Gradle@3
            displayName: 'ktlintCheck'
            inputs:
              workingDirectory: 'azure-communication-ui'
              gradleWrapperFile: 'azure-communication-ui/gradlew'
              gradleOptions: '-Xmx3072m'
              tasks: 'ktlintCheck'
          - task: Gradle@3
            displayName: 'calling compile, lint, test'
            inputs:
              workingDirectory: 'azure-communication-ui/calling'
              gradleWrapperFile: 'azure-communication-ui/gradlew'
              gradleOptions: '-Xmx3072m'
              publishJUnitResults: false
              tasks: ':calling:build --stacktrace'
          - task: Gradle@3
            displayName: 'chat compile, lint, test'
            inputs:
              workingDirectory: 'azure-communication-ui'
              gradleWrapperFile: 'azure-communication-ui/gradlew'
              gradleOptions: '-Xmx3072m'
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              tasks: ':chat:build --stacktrace'
          - task: Gradle@3
            displayName: 'build (compile, lint, test)'
            inputs:
              workingDirectory: 'azure-communication-ui'
              gradleWrapperFile: 'azure-communication-ui/gradlew'
              gradleOptions: '-Xmx3072m'
              publishJUnitResults: false
              tasks: 'build --stacktrace'
          - task: Gradle@3
            displayName: 'Coverage report for all packages'
            inputs:
              workingDirectory: 'azure-communication-ui'
              gradleWrapperFile: 'azure-communication-ui/gradlew'
              gradleOptions: '-Xmx3072m'
              publishJUnitResults: false
              tasks: ':combinedCoverageReport'
          - task: PublishCodeCoverageResults@2
            displayName: 'Calling - Publish code coverage report'
            inputs:
              summaryFileLocation: $(System.DefaultWorkingDirectory)/azure-communication-ui/build/reports/coverage/test/debug/report.xml
              reportDirectory: $(System.DefaultWorkingDirectory)/azure-communication-ui/build/reports/coverage/test/debug
          - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
            displayName: 'Component Detection'
